---

  localhost:
    hosts:
      localhost:
        ansible_connection: local

  k8s_nodes:
    children:
      initial:
      additional:

  initial:
    hosts:
      k8spi1:  # first node
        ansible_host: 172.26.20.11 # you can comment/remove this if the hostname is sufficient

  additional:
    hosts:
      k8spi2:
        ansible_host: 172.26.20.12
      k8spi3:
        ansible_host: 172.26.20.13
      k8spi4:
        ansible_host: 172.26.20.14

