  - name: calculate join command
    set_fact:
      microk8s_token: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
      microk8s_initial_ipv4: "{{ ansible_default_ipv4.address }}"
    when: inventory_hostname in groups.initial
    run_once: true

  - name: pass token to initial node (run `microk8s add-node`)
    shell: |
      microk8s add-node --token {{ microk8s_token }} --token-ttl 300
    when: inventory_hostname in groups.initial
    run_once: true

  - name: add hosts to cluster (run `microk8s join`)
    shell: |
      microk8s join {{ microk8s_initial_ipv4 }}:25000/{{ microk8s_token }}
    when: ansible_default_ipv4.address == item
